### ISSUE TITLE
Quick review comment

### ISSUE THREAD

**Issue by mumoshu** [d-kuro/scheduled-pod-autoscaler#33]
Hey! Thanks for sharing awesome project ☺️ 

I'd been reading code a bit and thought something on this line:

https://github.com/d-kuro/scheduled-pod-autoscaler/blob/faca96b1b178cf4b57e9a264aab03f6a32e3d509/controllers/autoscaling/scheduledpodautoscaler_controller.go#L212

Shouldn't we return an error here?

Otherwise, we seem to end up running `updateScheduleStatus` twice for each entry in `processSchedule`:

https://github.com/d-kuro/scheduled-pod-autoscaler/blob/faca96b1b178cf4b57e9a264aab03f6a32e3d509/controllers/autoscaling/scheduledpodautoscaler_controller.go#L208-L219

**Comment by d-kuro** [comment]
@mumoshu 
Thanks for finding the bug!
I've merged a pull request for a fix.
https://github.com/d-kuro/scheduled-pod-autoscaler/pull/34
